SKILL_SYNONYMS = {
    # Soft skills
    "communication": ["коммуникация", "коммуникативные навыки", "communication skills"],
    "teamwork": ["командная работа", "работа в команде", "team work"],
    "problem_solving": ["решение проблем", "problem solving", "аналитическое мышление"],
    "adaptability": ["адаптивность", "гибкость", "adaptability"],
    "leadership": ["лидерство", "управление командой", "leadership"],
    "creativity": ["креативность", "творческое мышление", "creativity"],
    "time_management": ["тайм-менеджмент", "управление временем", "time management"],
    "self_motivation": ["самомотивация", "self motivation", "мотивация"],
    "learning_ability": ["обучаемость", "способность к обучению", "learning ability"],
    "attention_to_detail": ["внимание к деталям", "attention to detail", "скрупулезность"],
    
    # Hard skills
    "python": ["питон", "python programming", "python development"],
    "javascript": ["js", "javascript programming", "javascript development"],
    "java": ["java programming", "java development"],
    "c++": ["cpp", "c plus plus", "c++ programming"],
    "sql": ["structured query language", "database querying"],
    "react": ["react.js", "reactjs", "react development"],
    "angular": ["angular.js", "angularjs", "angular development"],
    "vue": ["vue.js", "vuejs", "vue development"],
    "node.js": ["nodejs", "node", "node.js development"],
    "django": ["django framework", "django development"],
    "flask": ["flask framework", "flask development"],
    "fastapi": ["fast api", "fast-api", "fastapi framework"],
    "docker": ["docker containerization", "docker development"],
    "kubernetes": ["k8s", "kubernetes orchestration"],
    "aws": ["amazon web services", "aws cloud"],
    "azure": ["microsoft azure", "azure cloud"],
    "gcp": ["google cloud platform", "google cloud"],
    "git": ["git version control", "git development"],
    "ci_cd": ["continuous integration", "continuous deployment", "ci/cd"],
    "rest": ["rest api", "restful api", "rest development"],
    "graphql": ["graph ql", "graphql api"],
    "mongodb": ["mongo", "mongodb database"],
    "postgresql": ["postgres", "postgresql database"],
    "mysql": ["mysql database"],
    "redis": ["redis cache", "redis database"],
    "typescript": ["ts", "typescript development"],
    "html": ["html5", "html development"],
    "css": ["css3", "css development"],
    "sass": ["scss", "sass development"],
    "less": ["less css", "less development"],
    "webpack": ["webpack bundler"],
    "babel": ["babel transpiler"],
    "jest": ["jest testing"],
    "pytest": ["python testing", "pytest framework"],
    "selenium": ["selenium testing", "selenium automation"],
    "postman": ["postman api testing"],
    "jira": ["jira project management"],
    "confluence": ["confluence documentation"],
    "agile": ["agile methodology", "agile development"],
    "scrum": ["scrum methodology", "scrum development"],
    "kanban": ["kanban methodology", "kanban development"],
    "ux": ["user experience", "ux design"],
    "ui": ["user interface", "ui design"],
    "figma": ["figma design"],
    "sketch": ["sketch design"],
    "photoshop": ["adobe photoshop"],
    "illustrator": ["adobe illustrator"],
    "premiere": ["adobe premiere"],
    "after_effects": ["adobe after effects"],
    "blender": ["blender 3d"],
    "maya": ["autodesk maya"],
    "unity": ["unity game development"],
    "unreal": ["unreal engine", "unreal game development"],
    "android": ["android development"],
    "ios": ["ios development", "swift development"],
    "react_native": ["react native", "react-native"],
    "flutter": ["flutter development"],
    "tensorflow": ["tensorflow ml", "tensorflow ai"],
    "pytorch": ["pytorch ml", "pytorch ai"],
    "scikit-learn": ["scikit learn", "sklearn"],
    "pandas": ["pandas data analysis"],
    "numpy": ["numpy numerical computing"],
    "matplotlib": ["matplotlib visualization"],
    "seaborn": ["seaborn visualization"],
    "tableau": ["tableau visualization"],
    "power_bi": ["power bi", "powerbi"],
    "excel": ["microsoft excel"],
    "word": ["microsoft word"],
    "powerpoint": ["microsoft powerpoint"],
    "outlook": ["microsoft outlook"],
    "teams": ["microsoft teams"],
    "slack": ["slack communication"],
    "zoom": ["zoom video conferencing"],
    "trello": ["trello project management"],
    "asana": ["asana project management"],
    "notion": ["notion workspace"],
    "wordpress": ["wordpress development"],
    "shopify": ["shopify development"],
    "magento": ["magento development"],
    "woocommerce": ["woocommerce development"],
    "salesforce": ["salesforce crm"],
    "hubspot": ["hubspot crm"],
    "marketo": ["marketo marketing"],
    "mailchimp": ["mailchimp email marketing"],
    "google_analytics": ["ga", "google analytics"],
    "seo": ["search engine optimization"],
    "sem": ["search engine marketing"],
    "ppc": ["pay per click", "google ads"],
    "social_media": ["social media marketing"],
    "content_marketing": ["content marketing"],
    "email_marketing": ["email marketing"],
    "affiliate_marketing": ["affiliate marketing"],
    "influencer_marketing": ["influencer marketing"],
    "video_marketing": ["video marketing"],
    "mobile_marketing": ["mobile marketing"],
    "growth_hacking": ["growth hacking"],
    "data_science": ["data science"],
    "machine_learning": ["ml", "machine learning"],
    "deep_learning": ["dl", "deep learning"],
    "natural_language_processing": ["nlp", "natural language processing"],
    "computer_vision": ["cv", "computer vision"],
    "robotics": ["robotics engineering"],
    "iot": ["internet of things"],
    "blockchain": ["blockchain development"],
    "cryptocurrency": ["crypto", "cryptocurrency development"],
    "smart_contracts": ["smart contract development"],
    "web3": ["web 3.0", "web3 development"],
    "defi": ["decentralized finance"],
    "nft": ["non-fungible tokens"],
    "metaverse": ["metaverse development"],
    "ar": ["augmented reality"],
    "vr": ["virtual reality"],
    "mr": ["mixed reality"],
    "xr": ["extended reality"],
    "game_development": ["game dev", "game development"],
    "mobile_development": ["mobile dev", "mobile development"],
    "web_development": ["web dev", "web development"],
    "desktop_development": ["desktop dev", "desktop development"],
    "embedded_development": ["embedded dev", "embedded development"],
    "system_administration": ["sysadmin", "system admin"],
    "network_administration": ["network admin"],
    "database_administration": ["dba", "database admin"],
    "security": ["cybersecurity", "information security"],
    "devops": ["development operations"],
    "sre": ["site reliability engineering"],
    "qa": ["quality assurance"],
    "testing": ["software testing"],
    "automation": ["test automation"],
    "performance_testing": ["perf testing", "performance testing"],
    "security_testing": ["security testing"],
    "api_testing": ["api testing"],
    "mobile_testing": ["mobile testing"],
    "web_testing": ["web testing"],
    "desktop_testing": ["desktop testing"],
    "embedded_testing": ["embedded testing"],
    "system_testing": ["system testing"],
    "integration_testing": ["integration testing"],
    "unit_testing": ["unit testing"],
    "regression_testing": ["regression testing"],
    "smoke_testing": ["smoke testing"],
    "sanity_testing": ["sanity testing"],
    "exploratory_testing": ["exploratory testing"],
    "ad_hoc_testing": ["ad-hoc testing"],
    "monkey_testing": ["monkey testing"],
    "alpha_testing": ["alpha testing"],
    "beta_testing": ["beta testing"],
    "user_acceptance_testing": ["uat", "user acceptance testing"],
    "load_testing": ["load testing"],
    "stress_testing": ["stress testing"],
    "spike_testing": ["spike testing"],
    "endurance_testing": ["endurance testing"],
    "scalability_testing": ["scalability testing"],
    "volume_testing": ["volume testing"],
    "security_testing": ["security testing"],
    "penetration_testing": ["pen testing", "penetration testing"],
    "vulnerability_testing": ["vulnerability testing"],
    "compliance_testing": ["compliance testing"],
    "accessibility_testing": ["a11y", "accessibility testing"],
    "usability_testing": ["usability testing"],
    "compatibility_testing": ["compatibility testing"],
    "localization_testing": ["l10n", "localization testing"],
    "internationalization_testing": ["i18n", "internationalization testing"],
    "recovery_testing": ["recovery testing"],
    "maintainability_testing": ["maintainability testing"],
    "portability_testing": ["portability testing"],
    "reliability_testing": ["reliability testing"],
    "stability_testing": ["stability testing"],
    "robustness_testing": ["robustness testing"],
    "resilience_testing": ["resilience testing"],
    "fault_tolerance_testing": ["fault tolerance testing"],
    "disaster_recovery_testing": ["disaster recovery testing"],
    "business_continuity_testing": ["business continuity testing"],
    "data_migration_testing": ["data migration testing"],
    "data_integrity_testing": ["data integrity testing"],
    "data_security_testing": ["data security testing"],
    "data_privacy_testing": ["data privacy testing"],
    "data_governance_testing": ["data governance testing"],
    "data_quality_testing": ["data quality testing"],
    "data_validation_testing": ["data validation testing"],
    "data_verification_testing": ["data verification testing"],
    "data_reconciliation_testing": ["data reconciliation testing"],
    "data_archiving_testing": ["data archiving testing"],
    "data_backup_testing": ["data backup testing"],
    "data_restore_testing": ["data restore testing"],
    "data_recovery_testing": ["data recovery testing"],
    "data_retention_testing": ["data retention testing"],
    "data_deletion_testing": ["data deletion testing"],
    "data_anonymization_testing": ["data anonymization testing"],
    "data_pseudonymization_testing": ["data pseudonymization testing"],
    "data_encryption_testing": ["data encryption testing"],
    "data_decryption_testing": ["data decryption testing"],
    "data_compression_testing": ["data compression testing"],
    "data_decompression_testing": ["data decompression testing"],
    "data_transformation_testing": ["data transformation testing"],
    "data_aggregation_testing": ["data aggregation testing"],
    "data_disaggregation_testing": ["data disaggregation testing"],
    "data_normalization_testing": ["data normalization testing"],
    "data_denormalization_testing": ["data denormalization testing"],
} 